# Generated by Django 5.0.6 on 2024-05-19 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=12)),
                ('bg_color', models.CharField(max_length=12)),
                ('video_len', models.FloatField()),
                ('add_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
